### ISSUE TITLE
Help ? Beautify

### ISSUE THREAD

**Issue by di48l069** [theouteredge/cmdR#3]
Hi please fix help make it more attractive maybe like windows cmd

example

For more information on a specific command, type HELP command-name
ASSOC          Displays or modifies file extension associations.
ATTRIB         Displays or changes file attributes.
BREAK          Sets or clears extended CTRL+C checking.
BCDEDIT        Sets properties in boot database to control boot loading.
CACLS          Displays or modifies access control lists (ACLs) of files.
CALL           Calls one batch program from another.
COPY           Copies one or more files to another location.
DATE           Displays or sets the date.
DEL            Deletes one or more files.
DIR            Displays a list of files and subdirectories in a directory.
DISKPART       Displays or configures Disk Partition properties.
DOSKEY         Edits command lines, recalls Windows commands, and
               creates macros.
DRIVERQUERY    Displays current device driver status and properties.
ECHO           Displays messages, or turns command echoing on or off.
ENDLOCAL       Ends localization of environment changes in a batch file.
ERASE          Deletes one or more files.
EXIT           Quits the CMD.EXE program (command interpreter).

For more information on tools see the command-line reference in the online help.

**Comment by di48l069** [comment]
@theouteredge Hi, Is this this project dead?

**Comment by theouteredge** [comment]
Hi di48l069,

Are you still looking at this issue? I got CmdR to a state I was happy with and I've had a lot going on in the last year or so to spend anymore time on it. I still use it on a couple of project and if I need to write a C# command line app I'll continue to use it, but I've been working on Hadoopp/Scala/Spark so I've not had much need of it for a while.

If you want to improve the help layout you can overwrite the "?" command or create your own help command. The inbuilt one can be found here: [Standard Module](https://github.com/theouteredge/cmdR/blob/master/src/cmdR/Modules/StandardModule.cs)

I'll accept a pull request if you want to improve/change it

**Comment by di48l069** [comment]
Hi, Still looking at this issue but thought the project is dead so kinda gave um.. I was hoping in you spare time maybe you can beautify it but I understand you busy

**Comment by di48l069** [comment]
@theouteredge also if you planning on updating please change `route` to `help` make more sense,

Not sure why you given up on this project its a work of art

**Comment by di48l069** [comment]
@theouteredge I will make changes and send through pull request

**Comment by theouteredge** [comment]
@di48l069 thanks for the compliments on CmdR, its nice to know someone is using it and getting some use out of it :smile:
