### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by ghost** [theouteredge/cmdR#5]
Hi,

I was having a look at your future plans below >

> FUTURE PLANS
> 
> Startup message, so users can enter a message that will be displayed when cmdR.Run is called for the first time
> Allow the setting of text colours when using the built in console.
> Implement a way of pipeing commands together
> look at the way nodejs implements middlewhere with the next function
> Implement a verison of the ICmdRConsole interface that wil work with a wpf app, so we can test out the ICmdRConsole interface in something other than a console app
> Allow us to pump data from one command to annother, i.e. read file.txt |> count-words

There are two that caught my eye that is easy to implement

> Allow the setting of text colours when using the built in console.

This will be easy you can add something like this
`[CmdRoute("save", "Saves the changes made to the bank class", "#ff0000", true)]` This will set command color if needed but I honestly think that's not important unless the user is on form of drug haha

`CmdR.Console.WriteLine("foo", "color hex");` and this will set the writeline color

> Allow us to pump data from one command to annother, i.e. read file.txt |> count-words

This above would be beautiful

**Comment by theouteredge** [comment]
@di48l069 for the text I was thinking of something along those lines.

I was thinking of something like this:
`CmdR.Console.WriteLine("This is standard text, #yellow;This is yellow #white;this is white #000000;this is black")`

Some we would parse the text and look for `#something;` if found we would break up the text and replace with `Write("")` and change the colour for each part.

I also liked the option to put this in the Route definition as well. I think both should be implemented

**Comment by theouteredge** [comment]
@di48l069 with the piping of data from one command to another I'm not sure how complicated this could get... It might need some fundamental rewriting of how Commands and CmdR works...

But having said that the basic outline of this functionality is to add the ability to specify commands which can have data piped to them, probably in the route definition

These Commands would then need to read data from a new `IEnumerable` property on the console maybe `StandardIn` then any text written to `CmdR.Console.Write` or `CmdR.Console.WriteLine` would be redirected to the StandardIn property.

CmdR when then need to know which Command was writing to the Console and redirect the output as required.

We would also need to change how commands are Parsed and add some validation that data is only being piped to commands that can have data piped to them.

**Comment by ghost** [comment]
@theouteredge Sounds like a headache
