### ISSUE TITLE
Repro Transfer or Purchase

### ISSUE THREAD

**Issue by ghost** [theouteredge/cmdR#8]
Hi @theouteredge  are you willing to transfer or sell this project to me? 

I see it gathering dust and I would like to keep it under my wing and maintain it.
I will still keep it open source.

As I'm building my entire current project around it.

**Comment by theouteredge** [comment]
Hi @di48l069 

I'm glad you're still happy using it. I'm not sure what to make of your request, it brings up some interesting questions.

- First it feels a little odd to be selling an open source project...
- But a little extra cash is always good... and I don't have the time to keep developing it
- What if you end up making of money from the project in the future?
- What if you wanted to transfer the ownership to someone else in the future?
- Who would own the copyright?
- What if you decided at some later point to remove the project or the nuget packages? I still have live project which rely on cmdR
- Would we need to draw up a legal agreement?

I think you have my personal email, do you want to message me with a figure you were thinking of offering? I will do some research into these questions and how you actually go about transferring project on GitHub and the NuGet account

**Comment by ghost** [comment]
Hi @theouteredge,

Honestly I'm not planning on making any money on this and will keep it open source will keep your license and keep your commits.

Its easy transferring the repo you just go to repro setting and say transfer which is above delete.

I will add you to a project tonight and show you what I want to do with it. Honestly open source is the future I don't have any intentions of making money off please check out the project I invite you to latter and you will understand.

And if you like it maybe you don't have sell or transfer and gives you motivation to continue your amazing work on cmdR and maybe even contribute to mine.

Just my worry was one day you delete it and then I am screwed haha,
